name: ButtonTeleport
main: ca.strendin.ButtonTeleport.ButtonTeleport
version: 0.1
website: https://github.com/MarkStrendin/ElioTeleport
authors:
  - Mark Strendin
description: Button based teleporting

permissions:
 ButtonTeleport.admin:
  description: Ability to manage teleport regions
  default: op
commands:  
  btr:
    aliases: [bt]
    description: Handles creation and removal of teleports
    usage: |
           /<command>            